repos:
-   repo: local
    hooks:
    -   id: make-format
        name: make format
        entry: make format
        language: system
    -   id: make-test
        name: make test
        entry: make test
        language: system
